// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/helloworld.proto

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	api/helloworld.proto

It has these top-level messages:
	SayHelloRequest
	SayRepetitiveHelloRequest
	HelloReply
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type SayHelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SayHelloRequest) Reset()                    { *m = SayHelloRequest{} }
func (m *SayHelloRequest) String() string            { return proto.CompactTextString(m) }
func (*SayHelloRequest) ProtoMessage()               {}
func (*SayHelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SayHelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The request message containing the user's name and the number of times to say hello.
type SayRepetitiveHelloRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *SayRepetitiveHelloRequest) Reset()                    { *m = SayRepetitiveHelloRequest{} }
func (m *SayRepetitiveHelloRequest) String() string            { return proto.CompactTextString(m) }
func (*SayRepetitiveHelloRequest) ProtoMessage()               {}
func (*SayRepetitiveHelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SayRepetitiveHelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SayRepetitiveHelloRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SayHelloRequest)(nil), "helloworld.SayHelloRequest")
	proto.RegisterType((*SayRepetitiveHelloRequest)(nil), "helloworld.SayRepetitiveHelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Send repetitive greetings
	SayRepetitiveHello(ctx context.Context, in *SayRepetitiveHelloRequest, opts ...grpc.CallOption) (Greeter_SayRepetitiveHelloClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayRepetitiveHello(ctx context.Context, in *SayRepetitiveHelloRequest, opts ...grpc.CallOption) (Greeter_SayRepetitiveHelloClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Greeter_serviceDesc.Streams[0], c.cc, "/helloworld.Greeter/SayRepetitiveHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayRepetitiveHelloClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayRepetitiveHelloClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayRepetitiveHelloClient struct {
	grpc.ClientStream
}

func (x *greeterSayRepetitiveHelloClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *SayHelloRequest) (*HelloReply, error)
	// Send repetitive greetings
	SayRepetitiveHello(*SayRepetitiveHelloRequest, Greeter_SayRepetitiveHelloServer) error
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayRepetitiveHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SayRepetitiveHelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayRepetitiveHello(m, &greeterSayRepetitiveHelloServer{stream})
}

type Greeter_SayRepetitiveHelloServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayRepetitiveHelloServer struct {
	grpc.ServerStream
}

func (x *greeterSayRepetitiveHelloServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayRepetitiveHello",
			Handler:       _Greeter_SayRepetitiveHello_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/helloworld.proto",
}

func init() { proto.RegisterFile("api/helloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2c, 0xc8, 0xd4,
	0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x42, 0x88, 0x28, 0xa9, 0x72, 0xf1, 0x07, 0x27, 0x56, 0x7a, 0x80, 0x04, 0x82, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x57, 0x2e, 0xc9, 0xe0, 0xc4, 0xca, 0xa0, 0xd4, 0x82,
	0xd4, 0x92, 0xcc, 0x92, 0xcc, 0xb2, 0x54, 0x42, 0x1a, 0x84, 0x44, 0xb8, 0x58, 0x93, 0xf3, 0x4b,
	0xf3, 0x4a, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x20, 0x1c, 0x25, 0x35, 0x2e, 0x2e, 0xa8,
	0xce, 0x82, 0x9c, 0x4a, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0x74, 0x98, 0x56,
	0x18, 0xd7, 0x68, 0x29, 0x23, 0x17, 0xbb, 0x7b, 0x51, 0x6a, 0x6a, 0x49, 0x6a, 0x91, 0x90, 0x23,
	0x17, 0x07, 0xcc, 0x85, 0x42, 0xd2, 0x7a, 0x48, 0x9e, 0x41, 0x73, 0xb7, 0x94, 0x18, 0xb2, 0x24,
	0xc2, 0x1a, 0x25, 0x06, 0xa1, 0x70, 0x2e, 0x21, 0x4c, 0xd7, 0x0b, 0xa9, 0xa2, 0x19, 0x86, 0xdd,
	0x77, 0xb8, 0x8d, 0x35, 0x60, 0x74, 0x32, 0xe6, 0x92, 0xce, 0xcc, 0xd7, 0x4b, 0x2f, 0x2a, 0x48,
	0xd6, 0x4b, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x2d, 0x46, 0x52, 0xed, 0xc4, 0x0f, 0x56, 0x1e,
	0x0e, 0x62, 0x07, 0x80, 0x42, 0x3e, 0x80, 0xb1, 0x81, 0x91, 0x31, 0x89, 0x0d, 0x1c, 0x0b, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x2f, 0x52, 0x7e, 0x9d, 0x01, 0x00, 0x00,
}
